# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('client', 'client'),
        ('server', 'server'),
        ('init', 'init'),
        ('.env', '.'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'server.index',
        'server.api.users',
        'server.api.csv',
        'server.api.dashboard',
        'server.api.history',
        'server.libs.database.Config',
        'server.libs.database.RunQuery',
        'server.libs.jwt.jwt_utils',
        'server.libs.totp.totp_utils',
        'server.libs.users.Login',
        'server.libs.users.Register',
        'server.libs.csv.Add',
        'server.libs.csv.Drop',
        'server.libs.csv.Edit',
        'server.libs.csv.Get',
        'server.libs.csv.Read',
        'mysql.connector',
        'pandas',
        'bcrypt',
        'pyotp',
        'qrcode',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Qub',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon='icon.ico', 
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)